### ISSUE TITLE
[UX] provide a "Add non-linkable item" and a "Add separator item" action links instead of special paths.

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/special_menu_items#1]
We currently require the user to enter either `<nolink>` or `<separator>` as path in order to create the supported special menu items. That is for users that already know how the module works. Those that are not familiar with it, have to first read the instructions (who does that?).

What I would like to see is this:

![special_menu_items-action_links](https://cloud.githubusercontent.com/assets/2423362/6001279/02a243f4-ab3c-11e4-99ca-5bda40e18180.png)

...and/or a radio options set like this (By the way, the "Menu link title" label does not make sense when trying to add special menu items. It should be "Menu item title".):

![special_menu_items-menu_item_type_radio](https://cloud.githubusercontent.com/assets/2423362/6001797/8fc68cae-ab41-11e4-831f-7f71e0c65728.png)

**Comment by klonos** [comment]
By the way, the "Menu link title" label does not make sense when trying to add special menu items. It should be "Menu item title".

**Comment by docwilmot** [comment]
> Those that are not familiar with it, have to first read the instructions (who does that?).

Lol.

Will look at this.

**Comment by klonos** [comment]
Thank you for considering this. Which of the two solutions seems better UX-wise to you? The separate action links (and thus separate forms) or the single action/form with radio select options?

**Comment by jenlampton** [comment]
I like the idea of using radios on the current form :)

**Comment by klonos** [comment]
PS: for the "Separator item" option, we should hide/disable the "Menu item title" field (does not matter because it will not be rendered), but because it is required, perhaps auto-fill it with a `separator` value or something.

**Comment by stpaultim** [comment]
I just tried to create a menu item that linked to a PDF file in the files directory and got an error message. Would this help solve that problem?

https://forum.backdropcms.org/forum/how-create-menu-link-pdf

**Comment by jenlampton** [comment]
No, the menu system checks links to make sure they are registered system
paths. We need to remove that validation too.

**Comment by stpaultim** [comment]
I'm looking for a work-a-round solution right now that does not include hard-coding the entire path (including domain). https://forum.backdropcms.org/forum/how-create-menu-link-pdf

**Comment by laryn** [comment]
Started here but ran stuck and need to move on to other projects:
https://github.com/backdrop-contrib/special_menu_items/tree/issue-1

![Screen Shot 2020-03-11 at 2 35 22 PM](https://user-images.githubusercontent.com/871421/76456778-9348d900-63a5-11ea-897a-3d6b552c6f5c.jpg)

We can't set the value of the title or path based on the selection using `#states` so we'll need some JS or AJAX to do that, most likely.

**Comment by ghost** [comment]
@laryn Tried your code and the reason you're getting validation errors is because `#states` doesn't change form validation, just the presentation. You'll need to additionally unset the 'required' status in your custom validation function I think...

**Comment by docwilmot** [comment]
Better change it in the form alter itself: `$form['whatever']['#required'] = FALSE` But then you need to do a validation function to ensure that `whatever` is never empty.

**Comment by laryn** [comment]
Thanks @BWPanda and @docwilmot -- there's now a PR I'd love a review on.
https://github.com/backdrop-contrib/special_menu_items/pull/14
