### ISSUE TITLE
<nolink> items and core's dropdown menu functionality don't work well together

### ISSUE THREAD

**Issue by wesruv** [backdrop-contrib/special_menu_items#10]
Working on BackdropCMS.org I found a nasty bug this introduces with our Dropdown menu.

If you add a `<nolink>` element with children you're not able to get to the children. Since the dropdown functionality is 3rd party code it probably opens up a huge can o' worms.
![image](https://cloud.githubusercontent.com/assets/5607236/20735705/dbc5f96a-b66f-11e6-88b8-e3c71a14e1e1.png)

Might be that the menu output can be altered to make it work well with Smart Menus, might be that it's better just to leave as a caveat in the module's README.

**Comment by stpaultim** [comment]
I just ran into this problem as well and am testing https://backdropcms.org/project/menu_firstchild as a possible alternative. It seems to be working so far.

**Comment by laryn** [comment]
Special Menu Items has a configuration page at **/admin/config/system/special_menu_items** which allows you to specify the HTML tag to use. If you change the tag for `<nolink>` to be `<a>` then it seems to work on a parent menu item.

![Screen Shot 2019-11-08 at 12 05 09 AM](https://user-images.githubusercontent.com/871421/68453540-72843300-01bb-11ea-8eaa-71312551fd28.jpg)

**Comment by herbdool** [comment]
Nice find @laryn. Maybe `<a>` should be the default or is that a problem for accessibility?

**Comment by laryn** [comment]
Hmm.. 
https://stackoverflow.com/a/15885150/4122575

> While it may be completely valid HTML to not include an href, especially with an onclick handler, there are some things to consider: it will not be keyboard-focusable without having a tabindex value set. Furthermore, this will be inaccessible to screenreader software using Internet Explorer, as IE will report through the accessibility interfaces that any anchor element without an href attribute as not-focusable, regardless of whether the tabindex has been set.

> So while the following may be completely valid:

> `<a class="arrow">Link content</a>`

> It's far better to explicitly add a null-effect href attribute

> `<a href="javascript:void(0);" class="arrow">Link content</a>`

**Comment by laryn** [comment]
It looks like the D7 version has a few updates since this port, including [one related to tabindex](https://git.drupalcode.org/project/special_menu_items/commit/69502551c9921c43c224cf4c7182cf65fac634d0) on nolinks. And there's [an issue related to using `<a href='#'>` as the tag](https://www.drupal.org/project/special_menu_items/issues/1841836).

**Comment by herbdool** [comment]
Oh, the latter seems like a good idea.

**Comment by laryn** [comment]
Closing via https://github.com/backdrop-contrib/special_menu_items/commit/54e1f9e48ad976e4b2b8fbb46d8f50bb82b84928
