### ISSUE TITLE
Separators don't work on frontend

### ISSUE THREAD

**Issue by Razunter** [backdrop-contrib/special_menu_items#17]
Tried using v2.1.0, but the module doesn't work on frontend. In settings menu it looks ok, but on site separators render text `< class="separator">`.
Printing `$element` from `special_menu_items_link` shows empty `#href` on these items.

Backdrop v1.16.2

**Comment by laryn** [comment]
Hi @Razunter I'll take a look.

**Comment by laryn** [comment]
@Razunter Can you provide more info? Did you update any configuration settings or have any customized templates? What other modules are installed?

I activated on a sandbox and it looks good in the back end:
> ![Screen Shot 2020-09-14 at 1 13 34 PM](https://user-images.githubusercontent.com/871421/93122589-5f1fdf00-f68c-11ea-9975-03a265784019.jpg)

It also seems to be displaying in the front end correctly:
> ![Screen Shot 2020-09-14 at 1 14 29 PM](https://user-images.githubusercontent.com/871421/93122605-68a94700-f68c-11ea-9e1a-9a2f6132af46.jpg)

**Comment by Razunter** [comment]
Hm...
![preview](https://user-images.githubusercontent.com/362900/93124866-560a2e80-f6db-11ea-8da6-af459d59fbac.png)

```
<ul class="menu-dropdown menu" data-menu-style="dropdown" data-clickdown="1" data-menu-toggle-id="menu-toggle-state">
<li class="first leaf menu-mlid-382"><a href="/" title="" class="active">Главная</a></li>
<li class="leaf menu-mlid-1769">< class="separator"></></li>
```

Site was upgraded from Drupal 7, custom modules are: Backup & Migrate, Image Resize Filter, Special Menu Items.
Theme is based on "Basis" without many changes, I don't see anything that would affect this.

**Comment by laryn** [comment]
@Razunter What do you have in **admin/config/system/special_menu_items**?
Default is:
![Screen Shot 2020-09-14 at 1 54 15 PM](https://user-images.githubusercontent.com/871421/93126326-cdb36b80-f691-11ea-941e-a8ffa0efaddd.jpg)

**Comment by Razunter** [comment]
OK, I didn't notice that D7 site had special_menu_items too and missed the DB update.  Although it became like this: 
![bug](https://user-images.githubusercontent.com/362900/93126731-cd40c200-f6dd-11ea-819e-1981d83f9036.png)

But my issue is fixed now, thank you.
