### ISSUE TITLE
README.md needs an update

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/special_menu_items#2]
Looks like the README needs to be updated to meet Backdrop standards, particularly the module installation instructions. See https://github.com/backdrop-ops/contrib/blob/master/examples/README.md

Additionally, it looks like some of the text in the README is left over from Drupal 6...
`
Administer -> Site building -> Modules
`
Let's update to work for Backdrop, and if we're feeling generous, maybe post a patch back to Drupal 7 too :)

**Comment by laryn** [comment]
Closed via https://github.com/backdrop-contrib/special_menu_items/commit/3deab82ab3686b1b36fdf53efb8a9137f7eae983 and https://www.drupal.org/project/special_menu_items/issues/3119223
