### ISSUE TITLE
Breadcrumb implementations for `<nolink>` and `<separator>`

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/special_menu_items#22]
This issue was first mentioned in #21. I started a new issue since #21 was not specifically about breadcrumbs. 

Problem: breadcrumbs shown when you visit a page below any Special Menu Item include a link to <nolink> within the breadcrums.

**Comment by laryn** [comment]
@argiepiano Thanks! Looks pretty good. I have a few comments:

 - Can you add periods to the ends of the sentences in the docblock?
 - Can you implement a check for a `<separator>` href as well? We can probably just unset/take that separator out of the breadcrumb completely, do you agree?

**Comment by argiepiano** [comment]
@laryn, thanks. I will fix the periods.

Regarding your comment about `<separator>` - that is not needed. Breadcrumbs are only built for pages you can visit. You can't visit a separator page, thus you will never encounter a situation where you have to build breadcrumbs for a separator "page". Likewise, a separator can't really have children (technically you can insert a child under a separator, but they will never be displayed, and therefore no breadcrumb will be built. I tested that.)

So, I believe there is no need for implementing a check for separator in this patch, which only deals with breadcrumbs. 

If I'm missing or misunderstanding something, let me know.

**Comment by laryn** [comment]
@argiepiano 

I agree it's not really a correct way to set up a menu, but there is a condition where it's possible, and even though it's incorrect for the user to set up a menu this way, I think we might as well make the Breadcrumbs not contribute to the mess. 

Consider this menu:

> ![separator-submenu](https://user-images.githubusercontent.com/871421/133190124-376fb11a-c153-4c60-a550-0807d3557090.png)

If someone ends up on the "About" page, the breadcrumb shows the `<nolink>` item as well as the `<separator>` item (and with the current PR, both of these have a `/<separator>` href in the breadcrumb.

> ![separator-breadcrumb](https://user-images.githubusercontent.com/871421/133190238-bdfeb56a-318f-4836-9c18-92499d01ce70.png)

**Comment by argiepiano** [comment]
@laryn, got it. I'll add that fix tomorrow.

**Comment by laryn** [comment]
Merged https://github.com/backdrop-contrib/special_menu_items/pull/23 -- thanks @argiepiano!
