### ISSUE TITLE
Error when opening login/logout menu links

### ISSUE THREAD

**Issue by abetomas** [backdrop-contrib/special_menu_items#26]
I get a error message when I edit the login/logout links in standard "User Menu"

> Notice: Undefined index: #default_value in special_menu_items_form_menu_edit_item_alter() (line 153 of /Applications/MAMP/htdocs/rc-10/modules/special_menu_items/special_menu_items.module).

![Screen Shot 2022-07-17 at 10 34 30 PM](https://user-images.githubusercontent.com/9346415/179439484-1dcaf782-9065-4010-87e0-58b6c7b3350d.png)
"

**Comment by indigoxela** [comment]
> I get a error message when I edit the login/logout links in standard "User Menu"

The same notice happens with all menu items for which the path is controlled by modules (so it's not editable).

A simple [PR](https://github.com/backdrop-contrib/special_menu_items/pull/27) is available for testing and review.

**Comment by indigoxela** [comment]
There's a possibly related issue (not sure, though) re conflicts with menu views. I wonder if this PR also helps with that issue:  #18

Edit: nope, I don't think this PR helps in any way with the other issue.

**Comment by abetomas** [comment]
That was a quick response. thank you @indigoxela.

**Comment by abetomas** [comment]
I have applied the changes you 

> > I get a error message when I edit the login/logout links in standard "User Menu"
> 
> The same notice happens with all menu items for which the path is controlled by modules (so it's not editable).
> 
> A simple [PR](https://github.com/backdrop-contrib/special_menu_items/pull/27) is available for testing and review.

Hello @indigoxela .  Sorry for late reply.  I have applied the fixes in your [PR](https://github.com/backdrop-contrib/special_menu_items/pull/27)  and the error messages have disappeared.  
Thank you again.

**Comment by indigoxela** [comment]
@abetomas great, many thanks for verifying. No need to excuse, btw., replying withing a few days isn't actually "late". :wink:

I'm sure, @laryn - maintainer of this module - will take care of reviewing and merging as soon as he's available again.

**Comment by laryn** [comment]
Thanks to both of you, @abetomas for filing and @indigoxela for fixing! 

Merged based on a code review and your testing @abetomas -- thanks again.
