### ISSUE TITLE
Clicking on the special menu items from the manage menu links admin page leads to "page not found".

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/special_menu_items#7]
The requested page "/%3Cnolink%3E" could not be found.

The requested page "/%3Cseparator%3E" could not be found.

Perhaps render all `<nolink>` menu items as plain text instead of links and all `<separator>` menu items as a series of underscores or an `<hr>`?

**Comment by klonos** [comment]
Mockup:

![backdrop-contrib-special_menu_items-issue7_mockup-nolink_as_plain_text-separator_as_hr_tag](https://cloud.githubusercontent.com/assets/2423362/15094003/e594424e-14da-11e6-82bc-8a32cd1158e8.png)

**Comment by laryn** [comment]
@klonos Are you willing to test this one and spot check the code to see if it looks reasonable? https://github.com/backdrop-contrib/special_menu_items/commit/e50231d2ad81cdfc2d3f7ce5722167c28afb2df0

![Screen Shot 2020-03-11 at 12 38 34 PM](https://user-images.githubusercontent.com/871421/76446832-a2c02600-6395-11ea-840a-fea485daddd2.jpg)
